config/routes.rb
Rails.application.routes.draw do
  resources :"blog_posts"
  root to: "blog_posts#index"
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  skip_forgery_protection if Rails.env.development?

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[ show edit update destroy ]

  # GET /blog_posts or /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1 or /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts or /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: "Blog post was successfully created." }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1 or /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: "Blog post was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1 or /blog_posts/1.json
  def destroy
    @blog_post.destroy!

    respond_to do |format|
      format.html { redirect_to blog_posts_path, notice: "Blog post was successfully deleted.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, notice: "Post was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :body ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog_posts/_blog_post.html.erb
<div class="blog-post-card">
  <h2><%= @blog_post.title %></h2>
  <p><%= @blog_post.body %></p>

  <p>
    <%= link_to "Back", blog_posts_path, class: "btn btn-secondary" %>
    <%= link_to "Edit", edit_blog_post_path(@blog_post), class: "btn btn-primary" %>

    <%= form_with url: blog_post_path(@blog_post), method: :delete, data: { controller: "deletemodal" } do %>
      <%= submit_tag "Delete", class: "btn btn-danger" %>
    <% end %>
  </p>
</div>

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post, local: true) do |form| %>
  <% if blog_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
        <% blog_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<% content_for :title, "Editing blog post" %>

<h1>Editing blog post</h1>

<%= render "form", blog_post: @blog_post %>

<br>

<div>
  <%= link_to "Show this blog post", @blog_post %> |
  <%= link_to "Back to blog posts", blog_posts_path %>
</div>

app/views/blog_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Blog posts" %>

<h1>Blog posts</h1>

<div id="blog_posts">
  <% @blog_posts.each do |blog_post| %>
    <div class="blog-post-card">
      
      <h2><%= blog_post.title %></h2>
      
      <!-- truncated body -->
      <p class="post-body">
        <%= truncate(blog_post.body, length: 150) %>
      </p>

      <!-- More link -->
      <%= link_to blog_post_path(blog_post), class: "read-more" do %>
        <i class="fas fa-eye"></i>
      <% end %>

      <!-- edit/delete buttons, visible only on hover -->
      <div class="actions">
        <%= link_to edit_blog_post_path(blog_post), class: "btn btn-primary" do %>
          <i class="fas fa-edit"></i>
        <% end %>

        <%= form_with url: blog_post_path(blog_post), method: :delete, data: { controller: "deletemodal" } do %>
          <button>
            <i class="fas fa-trash"></i>
          </button>
        <% end %>
      </div>
      
    </div>
  <% end %>
</div>

<%= link_to "New blog post", new_blog_post_path, class: "new-post-link" %>

app/views/blog_posts/new.html.erb
<% content_for :title, "New blog post" %>

<h1>New blog post</h1>

<%= render "form", blog_post: @blog_post %>

<br>

<div>
  <%= link_to "Back to blog posts", blog_posts_path %>
</div>

app/views/blog_posts/show.html.erb
<%= link_to "Back to all blog posts", blog_posts_path, class:"back-link"%>

<div class="blog-post-card">
  <h2><%= @blog_post.title %></h2>
  <p><%= @blog_post.body %></p>

  <p>
    <%= link_to "edit", edit_blog_post_path(@blog_post) %>

    <%= form_with url: blog_post_path(@blog_post), method: :delete, data: { controller: "deletemodal" } do %>
      <%= submit_tag "Delete", class: "delete-button" %>
    <% end %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "MicroMuse" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="MicroMuse">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <!-- Modal -->
    <div id="confirm-modal" class="confirm-modal hidden" data-controller="confirmmodal">
      <div class="confirm-modal-content">
        <p>Are you sure you want to delete this?</p>
        <button id="confirm-yes" data-action="click->confirmmodal#yes">Yes</button>
        <button id="confirm-no" data-action="click->confirmmodal#no">No</button>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div>
    <strong>Title:</strong>
    <%= post.title %>
  </div>

  <div>
    <strong>Body:</strong>
    <%= post.body %>
  </div>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>